In [3]:
import pandas as pd

# Carga el archivo CSV usando una codificación alternativa
df = pd.read_csv("C:/Users/USUARIO/Downloads/Global_Education.csv", encoding='ISO-8859-1')

In [4]:
# Calcula  estadisticos descriptivos
df.describe()

,Latitude,Longitude,OOSR_Pre0Primary_Age_Male,OOSR_Pre0Primary_Age_Female,OOSR_Primary_Age_Male,OOSR_Primary_Age_Female,OOSR_Lower_Secondary_Age_Male,OOSR_Lower_Secondary_Age_Female,OOSR_Upper_Secondary_Age_Male,OOSR_Upper_Secondary_Age_Female,...,Primary_End_Proficiency_Reading,Primary_End_Proficiency_Math,Lower_Secondary_End_Proficiency_Reading,Lower_Secondary_End_Proficiency_Math,Youth_15_24_Literacy_Rate_Male,Youth_15_24_Literacy_Rate_Female,Birth_Rate,Gross_Primary_Education_Enrollment,Gross_Tertiary_Education_Enrollment,Unemployment_Rate
count,202.000000,202.000000,202.000000,202.000000,202.000000,202.000000,202.000000,202.000000,202.000000,202.000000,...,202.000000,202.000000,202.000000,202.000000,202.000000,202.000000,202.000000,202.000000,202.000000,202.000000
mean,25.081422,55.166928,19.658416,19.282178,5.282178,5.569307,8.707921,8.831683,20.292079,19.975248,...,10.717822,10.376238,25.787129,24.450495,35.801980,35.084158,18.914010,94.942574,34.392574,6.000000
std,16.813639,45.976287,25.007604,25.171147,9.396442,10.383092,13.258203,14.724717,21.485592,23.140376,...,24.866101,22.484423,33.181384,31.965467,45.535186,45.249643,10.828184,29.769338,29.978206,5.273136
min,0.023559,0.824782,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,11.685062,18.665678,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.250000,0.250000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,10.355000,97.200000,9.000000,2.302500
50%,21.207861,43.518091,9.000000,7.000000,1.000000,1.000000,2.000000,2.000000,15.000000,12.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,17.550000,101.850000,24.850000,4.585000
75%,39.901792,77.684945,31.000000,30.000000,6.000000,6.750000,12.750000,10.750000,32.750000,30.000000,...,0.000000,0.000000,56.750000,50.750000,94.000000,96.750000,27.692500,107.300000,59.975000,8.655000
max,64.963051,178.065032,96.000000,96.000000,58.000000,67.000000,61.000000,70.000000,84.000000,89.000000,...,99.000000,89.000000,89.000000,94.000000,100.000000,100.000000,46.080000,142.500000,136.600000,28.180000

# Calcular la mediana

In [5]:
median = df.median(numeric_only=True)
print("Mediana:\n", median)

Mediana:
 Latitude                                    21.207861
Longitude                                   43.518091
OOSR_Pre0Primary_Age_Male                    9.000000
OOSR_Pre0Primary_Age_Female                  7.000000
OOSR_Primary_Age_Male                        1.000000
OOSR_Primary_Age_Female                      1.000000
OOSR_Lower_Secondary_Age_Male                2.000000
OOSR_Lower_Secondary_Age_Female              2.000000
OOSR_Upper_Secondary_Age_Male               15.000000
OOSR_Upper_Secondary_Age_Female             12.000000
Completion_Rate_Primary_Male                37.500000
Completion_Rate_Primary_Female              33.000000
Completion_Rate_Lower_Secondary_Male        18.500000
Completion_Rate_Lower_Secondary_Female      12.000000
Completion_Rate_Upper_Secondary_Male         9.500000
Completion_Rate_Upper_Secondary_Female       5.500000
Grade_2_3_Proficiency_Reading                0.000000
Grade_2_3_Proficiency_Math                   0.000000
Primary_End_Proficiency_Reading              0.000000
Primary_End_Proficiency_Math                 0.000000
Lower_Secondary_End_Proficiency_Reading      0.000000
Lower_Secondary_End_Proficiency_Math         0.000000
Youth_15_24_Literacy_Rate_Male               0.000000
Youth_15_24_Literacy_Rate_Female             0.000000
Birth_Rate                                  17.550000
Gross_Primary_Education_Enrollment         101.850000
Gross_Tertiary_Education_Enrollment         24.850000
Unemployment_Rate                            4.585000
dtype: float64

# Calcular Desviacion Estandar

In [6]:
std_dev = df.std(numeric_only=True)
print("Desviación estándar:\n", std_dev)

Desviación estándar:
 Latitude                                   16.813639
Longitude                                  45.976287
OOSR_Pre0Primary_Age_Male                  25.007604
OOSR_Pre0Primary_Age_Female                25.171147
OOSR_Primary_Age_Male                       9.396442
OOSR_Primary_Age_Female                    10.383092
OOSR_Lower_Secondary_Age_Male              13.258203
OOSR_Lower_Secondary_Age_Female            14.724717
OOSR_Upper_Secondary_Age_Male              21.485592
OOSR_Upper_Secondary_Age_Female            23.140376
Completion_Rate_Primary_Male               42.162708
Completion_Rate_Primary_Female             43.099714
Completion_Rate_Lower_Secondary_Male       36.438123
Completion_Rate_Lower_Secondary_Female     38.040452
Completion_Rate_Upper_Secondary_Male       28.604850
Completion_Rate_Upper_Secondary_Female     30.487827
Grade_2_3_Proficiency_Reading              34.873326
Grade_2_3_Proficiency_Math                 29.751858
Primary_End_Proficiency_Reading            24.866101
Primary_End_Proficiency_Math               22.484423
Lower_Secondary_End_Proficiency_Reading    33.181384
Lower_Secondary_End_Proficiency_Math       31.965467
Youth_15_24_Literacy_Rate_Male             45.535186
Youth_15_24_Literacy_Rate_Female           45.249643
Birth_Rate                                 10.828184
Gross_Primary_Education_Enrollment         29.769338
Gross_Tertiary_Education_Enrollment        29.978206
Unemployment_Rate                           5.273136
dtype: float64